# Generated by Django 5.2.7 on 2026-04-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='session_mode',
            field=models.CharField(choices=[('MONARCHY', 'Monarchy'), ('ANARCHY', 'Anarchy')], default='ANARCHY', max_length=20),
        ),
    ]
