# Generated by Django 5.2.7 on 2025-10-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_cardimage_delete_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardimage',
            name='image',
            field=models.ImageField(upload_to='card_images/'),
        ),
    ]
