# Generated by Django 5.2.7 on 2026-02-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_sound'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sound',
        ),
    ]
